### ISSUE TITLE
大佬尽快优化clash吧

### ISSUE THREAD

**Issue by shunlongyang** [likuai2010/auto-installer#1]
现在的clash问题还太多了，很多节点在安卓上测速正常，在Next上测不到速度，链接延迟也非常大

**Comment by likuai2010** [comment]
在等公测版，没有公测版我也优化不了呀

**Comment by shunlongyang** [comment]
> 在等公测版，没有公测版我也优化不了呀

加油加油，有好的hap是大家侧载安装的原动力。clash貌似还会被杀后台

**Comment by MyGoodbye** [comment]
clash用一会就会失效，需要重启clash

**Comment by Shura23** [comment]
> 在等公测版，没有公测版我也优化不了呀

我想要hiddify-next，希望能有这个软件的鸿蒙版

**Comment by likuai2010** [comment]
已修复
