### ISSUE TITLE
重签名后的包目录

### ISSUE THREAD

**Issue by yabi-zzh** [likuai2010/auto-installer#14]
请问下，重签名后的包目录在哪里

**Comment by likuai2010** [comment]
用户目录下的 .autoPublisher

**Comment by yabi-zzh** [comment]
> 用户目录下的 .autoPublisher

找到了谢谢！

再请教个问题，就是我在AppGallery Connect中把设备的udid都录进去了，重签名后的包能直接在所有设备上安装吗，还是说需要一个个安装

**Comment by likuai2010** [comment]
每次安装的都是都会检测设备udid 没有会自动注册的

**Comment by likuai2010** [comment]
> > 用户目录下的 .autoPublisher
> 
> 找到了谢谢！
> 
> 再请教个问题，就是我在AppGallery Connect中把设备的udid都录进去了，重签名后的包能直接在所有设备上安装吗，还是说需要一个个安装

可以在你录的设备上安装不需要重新签名，每个账号只有100台设备
