### ISSUE TITLE
软件版本NEXT.0.0.70 ClashMeta代理-规则模式无法进入设置页面

### ISSUE THREAD

**Issue by ChoHope** [likuai2010/auto-installer#18]
Pura 70 Ultra现在软件版本是NEXT.0.0.70，ClashMeta代理-规则模式无法进入设置页面，是不是只能等系统软件版本更新到NEXT.0.0.71及以上才可以？

**Comment by likuai2010** [comment]
系统api问题， Pura 70 等部分机型api不支持，后续解决
