### ISSUE TITLE
Error: 安装失败

### ISSUE THREAD

**Issue by wgetnz** [likuai2010/auto-installer#23]
Error: 安装失败: error: failed to install bundle. code:9568305 error: Failed to install the HAP or HSP because the dependent module does not exist. entry's dependent module: library_mpaas_adapter does not exist

**Comment by ywlzou** [comment]
[Info]App install path:/Users/test/Downloads/auto-installer.hap, queuesize:0, msg:error: failed to install bundle. code:9568320 error: no signature file.
AppMod finish
