### ISSUE TITLE
Error: 连接失败，请检查地址192.168.101.44

### ISSUE THREAD

**Issue by zhouzhinian** [likuai2010/auto-installer#24]
前几天，我测试是可以安装运行，但是今天测试autoinstaller 2个版本都不行了，连接失败

![图片](https://github.com/user-attachments/assets/542bcda6-9991-416e-9e5b-f443d7156a2c)

**Comment by zhouzhinian** [comment]
测试手机：NOVA 12 Ultra星耀版 OS:harmonyos next (5.0.0.102 SP2C00E102RP8)

**Comment by 961739124** [comment]
端口呢

**Comment by zhouzhinian** [comment]
> 端口呢

加了端口也是不行啊
