### ISSUE TITLE
使用该工具会删除已有的调试证书

### ISSUE THREAD

**Issue by AskQi** [likuai2010/auto-installer#25]
此前在agc里有配置调试证书和发布和证书，使用本软件后只剩下发布证书了，之前名为debug的调试证书被删除，只剩下一个叫xiaobai-debug的调试证书

**Comment by ipad4** [comment]
建议增加手动导入证书功能，类似轻松签那种

**Comment by likuai2010** [comment]
> 此前在agc里有配置调试证书和发布和证书，使用本软件后只剩下发布证书了，之前名为debug的调试证书被删除，只剩下一个叫xiaobai-debug的调试证书

调试证书 华为限制了最多两个，为了防止xiaobai-debug无法创建，会自动删除已有的证书
