### ISSUE TITLE
请问有HAP包可供下载么？

### ISSUE THREAD

**Issue by ttcath** [likuai2010/auto-installer#3]
请问有HAP包可供下载么？盼答

**Comment by 961739124** [comment]
发布页就有啊

**Comment by ttcath** [comment]
> 发布页就有啊

没看到呢

**Comment by 961739124** [comment]
> > 发布页就有啊
> 
> 没看到呢
![Clip_2024-10-11_23-54-40](https://github.com/user-attachments/assets/f5dd2f47-eee0-4c45-b2eb-20d66d291d6d)
